const slideshows = {
    1: {
        name: "Intro",
        directives: [
            ["image", "1"],
            ["text", "The year is 2078."],
            ["image", "2"],
            ["text", "Gacha gaming has become a way of life."],
            ["text", "The thrilling experience of not knowing what items you'll get, the satisfying feeling when you get a rare {draw}, the flexibility and easiness to add gacha mechanics to every game in existence..."],
            ["text", "People have found gacha games to be the best way to pass time, for casual players and the more competitive-minded players alike."],
            ["text", "Though, when people talk about gacha games, that's not the most significant point to keep in mind."],
            ["text", "It's the fact that..."],
            ["image", "3"],
            ["text", "They make a <i>lot</i> of money."],
            ["text", "The gacha gaming scene has grown into a multi-millillion-dollar worth industry, far greater than any entertainment scene's worth, combined."],
            ["text", "To chase the money, billions of gacha games are coming out every single blink of an eye."],
            ["text", "Of course, since the market has become diluted with so many games, they need a way to introduce itself to players and prove that they're worth their time."],
            ["image", "4"],
            ["text", "Enter the advertising scene."],
            ["text", "Companies initially advertised their games by showing them good graphics and great gameplay mechanics."],
            ["text", "But, that didn't seem to attract lots of players."],
            ["text", "Eventually, they discovered that the most effective way to market a game is... to just give them lots of free stuff."],
            ["text", "After all, virtual currencies and {draws} are in fact, virtual and can be given as much as the company wants."],
            ["text", "As players get used to the larger numbers though, as soon as companies know it, players kept asking for more."],
            ["text", "Companies can't afford to not give more, there will always be a game that decides to give more stuff and thus get more players and money."],
            ["text", "In order to keep up with this, games kept giving more and more free stuff, until the numbers are so inflated they no longer has any real life meaning."],
            ["image", "5"],
            ["text", "You, a person in this society, lying in bed, are about to pick up a new gacha game."],
            ["image", "6"],
            ["text", "Omega Cards, for the mobile devices, the first game of its kind to advertise a trillion free card {draws}. The number that's one followed by twelve zeroes."],
            ["text", "To people 50 years ago, that sounded like a crazy amount of free {draws} to give, but the scene has caught up so fast that it's now just a lesser number compared to other games."],
            ["text", "Though, you still see people on the internet come back to it from time to time for the nostalgia values."],
            ["image", "5"],
            ["text", "You found it interesting enough to start the game for the first time, though the game wants you to use up your one trillion {draws} first."],
            ["text", "And that's when you realize..."],
            ["image", "7"],
            ["text", "...you will definitely be here for a while."],
        ]
    }
}